apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: {{.Values.deployment.replicas}} 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{.Values.deployment.imageVersion}} 
        ports:
        - containerPort: 80
        resouces:
          requests:
            cpu : 500m
            memory: 500Mi
          limits:
            cpu: 600m
            memory: 600Mi