apiVersion: v1
kind: Service
metadata:
  name : nginx-service
spec:
  selector:
     app: nginx
  type: LoadBalancer
  ports:
  - name: nginx
    port: {{.Values.service.portNumber}} #80
    targetPort: 80
    protocol: TCP