apiVersion: v1
kind: Pod
metadata:
  name: pod1
  purpose: podaffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: purpose
            operator: In
            values:
            - podaffinity
  containers:
  - name: nginx
    image: ngin-alpine:1.23.3