apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  affinity:
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #       - key: purpose
    #         operator: In
    #         values:
    #         - podaffinity
    #     topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: purpose
              operator: In
              values:
              - podaffinity
          topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: nginx:1.23.3-alpine
    