apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::816600798829:role/eksctl-ganesh-eks-nodegroup-worker-NodeInstanceRole-ys1re9lFN2D8
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-30T16:52:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1288"
  uid: d882b488-68b5-454c-83a6-23025e51a502
mapUsers: |
    - userarn: arn:aws:iam::816600798829:user/devuser
      username: devUser